### PR TITLE
could you merge updates following?

### PR DESCRIPTION
**Pull request by obuk**
- rewrites ssl_opts uinsg !perl/object in ~/.mcpani_remote
- uses Dist::Metadata to get -module and -modversion

### CODE REVIEW

**Comment by obuk** [comment]
I found an exception. Last commit 8d4b46c is fixes to my pullreq. It adds grep before sort to determine the module that has a version.

**Comment by Potatohead** [comment]
Hey,

The Dist::Metadata changes are good, I need to set it up and give it a test.

The ssl_opts need work. I'm not happy with people being able to pass in a class for the ssl_opts object and especially using the odd YAML line to do it. I suggest making CPAN::Mini::Inject::Remote::ssl_opts not inherit CACertOrg::CA and to instead use CACertOrg::CA to get a default value for SSL_ca_file. Also change 'our @OPTS' to 'my @OPTS', there should be no necessity for that to be global.

Thanks,
-Chris

**Comment by obuk** [comment]
Hi Chris,

Because it is worry, I intend to test it for a while.

Thanks,
obuk

**Comment by obuk** [comment]
Hi Chris,

490cdf0d7eff53f9bcbb1674044c0a41650120e4 ssl_opts changes are follows:
- not inherit CACertOrg::CA
- 'our @OPTS' to 'my @OPTS'

mcpani_remote:
- use Dist::Metadata

Thanks,
obuk

**Comment by obuk** [comment]
cc6c393ed6123b58ae9b903f99b7d3a898e45ec2 adds tests for odd yaml

and run cover -test

```
---------------------------- ------ ------ ------ ------ ------ ------ ------
File                           stmt   bran   cond    sub    pod   time  total
---------------------------- ------ ------ ------ ------ ------ ------ ------
MY/ssl_opts.pm                100.0  100.0    n/a  100.0  100.0    0.1  100.0
...PAN/Mini/Inject/Remote.pm   71.4   35.7   50.0   83.3  100.0   76.7   65.9
...Inject/Remote/ssl_opts.pm  100.0  100.0   33.3  100.0  100.0   23.1   93.5
Total                          78.5   43.7   44.4   90.0  100.0  100.0   73.8
---------------------------- ------ ------ ------ ------ ------ ------ ------
```

**Pull request closed without merging**
